# Generated by Django 4.2.6 on 2024-03-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinik', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='nom',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='id',
            new_name='id_produit',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='stock',
            new_name='quantite',
        ),
    ]
