# Generated by Django 4.2.6 on 2024-03-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinik', '0003_rename_quantite_vente_quantite_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
