# Generated by Django 4.2.6 on 2024-03-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinik', '0008_utilisateur_is_active_utilisateur_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
