# Generated by Django 4.2.6 on 2024-03-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinik', '0009_utilisateur_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='last_login',
        ),
    ]
