# Generated by Django 4.2.6 on 2024-03-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinik', '0010_remove_utilisateur_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportmensuel',
            name='mois',
            field=models.DateField(unique=True),
        ),
    ]
