# Generated by Django 4.2.6 on 2024-03-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinik', '0014_alter_rapportmensuel_patients_examines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportmensuel',
            name='mois',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='rapportmensuel',
            name='patients_consultes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rapportmensuel',
            name='patients_examines',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rapportmensuel',
            name='patients_hospitalises',
            field=models.IntegerField(),
        ),
    ]
