# Generated by Django 4.2.6 on 2024-03-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinik', '0015_alter_rapportmensuel_mois_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportmensuel',
            name='benefice_realise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rapportmensuel',
            name='montant_ventes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rapportmensuel',
            name='patients_consultes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rapportmensuel',
            name='patients_examines',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rapportmensuel',
            name='patients_hospitalises',
            field=models.IntegerField(default=0),
        ),
    ]
