# Generated by Django 4.2.6 on 2024-03-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinik', '0016_alter_rapportmensuel_benefice_realise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportmensuel',
            name='mois',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
